import type { Locale } from "../i18n";

/**
 * Legal document sections represented as paragraphs.
 * A section has a title and a body (can be plain text or an array of paragraphs).
 */
export type LegalSection = {
  title: string;
  body: string | string[];
};

export type LegalDocument = {
  title: string;
  lastUpdated: string;
  disclaimer: string;
  sections: LegalSection[];
};

export type LegalDictionaries = {
  privacyPolicy: LegalDocument;
  cookiePolicy: LegalDocument;
  legalNotice: LegalDocument;
  termsConditions: LegalDocument;
};

const es: LegalDictionaries = {
  privacyPolicy: {
    title: "Política de Privacidad",
    lastUpdated: "[FECHA]",
    disclaimer:
      "⚠️ Este documento es un MOCKUP no definitivo. Los campos marcados entre corchetes [ ] deben completarse con los datos reales antes de la publicación oficial.",
    sections: [
      {
        title: "1. Responsable del tratamiento",
        body: [
          "El responsable del tratamiento de los datos personales recogidos a través de este sitio web es:",
          "Titular: [NOMBRE / RAZÓN SOCIAL]",
          "NIF/CIF: [NIF/CIF]",
          "Domicilio: [DIRECCIÓN POSTAL]",
          "Correo electrónico: [EMAIL DE CONTACTO]",
          "Sitio web: https://3dcosprops.com/",
          "",
          'En adelante, el responsable será denominado "3DCosprops" o "el Responsable".',
          "",
          "[SI EXISTE DELEGADO DE PROTECCIÓN DE DATOS, AÑADIR SUS DATOS DE CONTACTO.]",
        ],
      },
      {
        title: "2. Ámbito de aplicación",
        body: [
          "Esta Política de Privacidad se aplica a los datos personales que puedan ser recopilados a través del sitio web de 3DCosprops, así como a las comunicaciones que los usuarios mantengan con nosotros mediante formularios, correo electrónico u otros medios habilitados en la plataforma.",
          "La presente política no se aplica a sitios web, aplicaciones o servicios de terceros a los que pueda accederse mediante enlaces incluidos en nuestra página web.",
          "Dichos servicios cuentan con sus propias políticas de privacidad y protección de datos.",
        ],
      },
      {
        title: "3. Datos personales que podemos recopilar",
        body: [
          "Dependiendo de las funcionalidades utilizadas por el usuario, podemos recopilar diferentes categorías de datos personales.",
          "",
          "3.1. Datos identificativos y de contacto",
          "Podemos recopilar, entre otros:",
          "- Nombre y apellidos.",
          "- Dirección de correo electrónico.",
          "- Número de teléfono, cuando sea necesario.",
          "- Dirección postal, cuando sea necesaria para la prestación de determinados servicios.",
          "- Nombre de usuario o identificador de cuenta.",
          "",
          "3.2. Datos de cuenta",
          "Si el sitio web permite crear una cuenta de usuario, podremos tratar información relacionada con dicha cuenta, como:",
          "- Dirección de correo electrónico.",
          "- Nombre de usuario.",
          "- Identificadores internos de usuario.",
          "- Información necesaria para gestionar la autenticación.",
          "- Preferencias asociadas a la cuenta.",
          "- Fecha de creación y actividad de la cuenta.",
          "Las contraseñas, cuando existan, no serán almacenadas directamente por 3DCosprops en texto plano, sino mediante los mecanismos de autenticación y seguridad proporcionados por los servicios tecnológicos utilizados para ello.",
          "",
          "3.3. Datos proporcionados mediante formularios",
          "Cuando el usuario contacte con nosotros o utilice un formulario de la web, podremos tratar los datos que voluntariamente facilite, por ejemplo:",
          "- Nombre.",
          "- Correo electrónico.",
          "- Asunto.",
          "- Mensaje.",
          "- Información adicional incluida voluntariamente por el usuario.",
          "Recomendamos no incluir en los formularios información especialmente sensible que no sea necesaria para gestionar la solicitud.",
          "",
          "3.4. Datos técnicos y de navegación",
          "Cuando el usuario navega por el sitio web, determinados datos técnicos pueden ser procesados automáticamente, dependiendo de la configuración y servicios utilizados por la plataforma.",
          "Estos datos pueden incluir:",
          "- Dirección IP.",
          "- Tipo y versión del navegador.",
          "- Sistema operativo.",
          "- Dispositivo utilizado.",
          "- Fecha y hora de acceso.",
          "- Información relativa a la navegación.",
          "- Datos necesarios para mantener la seguridad y funcionamiento del sitio web.",
          "- Información relacionada con errores o incidencias técnicas.",
          "La recopilación concreta de estos datos dependerá de la configuración definitiva de la infraestructura de 3DCosprops.",
        ],
      },
      {
        title: "4. Finalidades del tratamiento",
        body: [
          "Los datos personales podrán ser tratados para las siguientes finalidades:",
          "",
          "4.1. Gestión de cuentas de usuario",
          "Cuando el usuario disponga de una cuenta, utilizaremos sus datos para:",
          "- Crear y gestionar su cuenta.",
          "- Permitir el acceso a las funcionalidades correspondientes.",
          "- Gestionar la autenticación.",
          "- Mantener la seguridad de la cuenta.",
          "- Gestionar las preferencias del usuario.",
          "- Enviar comunicaciones relacionadas con la cuenta.",
          "",
          "4.2. Gestión de consultas y comunicaciones",
          "Los datos proporcionados mediante formularios de contacto o correo electrónico podrán utilizarse para:",
          "- Responder a consultas.",
          "- Gestionar solicitudes.",
          "- Mantener comunicaciones relacionadas con dichas solicitudes.",
          "- Proporcionar información solicitada por el usuario.",
          "",
          "4.3. Prestación de servicios",
          "Cuando corresponda, podremos tratar los datos necesarios para:",
          "- Gestionar pedidos, solicitudes o servicios.",
          "- Gestionar procesos de compra o contratación.",
          "- Coordinar la entrega de productos o servicios.",
          "- Gestionar incidencias relacionadas con los mismos.",
          "- Cumplir las obligaciones derivadas de una relación contractual.",
          "",
          "4.4. Seguridad y funcionamiento de la plataforma",
          "Podremos tratar determinados datos técnicos para:",
          "- Detectar y prevenir usos fraudulentos o abusivos.",
          "- Mantener la seguridad de la plataforma.",
          "- Detectar errores.",
          "- Prevenir accesos no autorizados.",
          "- Mantener y mejorar el funcionamiento técnico del sitio web.",
          "",
          "4.5. Cumplimiento de obligaciones legales",
          "Los datos podrán ser tratados cuando sea necesario para cumplir las obligaciones legales aplicables a 3DCosprops.",
        ],
      },
      {
        title: "5. Base jurídica del tratamiento",
        body: [
          "La base jurídica para el tratamiento de los datos dependerá de la finalidad concreta.",
          "Con carácter general, podremos tratar los datos personales sobre las siguientes bases jurídicas:",
          "- Ejecución de un contrato: cuando el tratamiento sea necesario para prestar un servicio solicitado por el usuario o gestionar una relación contractual.",
          "- Consentimiento: cuando el usuario haya otorgado su consentimiento para una finalidad concreta, por ejemplo, determinadas comunicaciones comerciales o cookies no necesarias.",
          "- Interés legítimo: cuando exista un interés legítimo de 3DCosprops y el tratamiento sea compatible con los derechos y libertades del usuario.",
          "- Cumplimiento de obligaciones legales: cuando el tratamiento sea necesario para cumplir una obligación legal aplicable.",
          "Cuando el tratamiento se base en el consentimiento, el usuario podrá retirarlo en cualquier momento. La retirada del consentimiento no afectará a la licitud de los tratamientos realizados con anterioridad a dicha retirada.",
        ],
      },
      {
        title: "6. Datos obligatorios y voluntarios",
        body: [
          "Los formularios del sitio web indicarán, cuando corresponda, qué campos son obligatorios y cuáles son opcionales.",
          "Los datos marcados como obligatorios serán necesarios para poder proporcionar el servicio o gestionar la solicitud correspondiente.",
          "Si el usuario no proporciona los datos necesarios, es posible que no podamos atender su solicitud, crear su cuenta o proporcionar determinadas funcionalidades.",
        ],
      },
      {
        title: "7. Destinatarios de los datos",
        body: [
          "Con carácter general, 3DCosprops no venderá los datos personales de sus usuarios.",
          "Para poder prestar determinados servicios y mantener la infraestructura tecnológica de la plataforma, algunos datos podrán ser tratados por proveedores tecnológicos que actúen como encargados del tratamiento o que presten servicios relacionados con el funcionamiento de la plataforma.",
          "Entre los proveedores tecnológicos utilizados o que podrán utilizarse se encuentran:",
          "",
          "Supabase",
          "Podremos utilizar Supabase para servicios relacionados con bases de datos, autenticación, almacenamiento u otras funcionalidades de backend.",
          "",
          "Vercel",
          "Podremos utilizar Vercel como proveedor de infraestructura y alojamiento para la aplicación web.",
          "",
          "Resend",
          "Podremos utilizar Resend para el envío y gestión técnica de correos electrónicos relacionados con la plataforma, como emails de contacto, autenticación, confirmaciones o comunicaciones transaccionales.",
          "",
          "Otros proveedores podrán incorporarse cuando resulte necesario para el funcionamiento de la plataforma.",
          "Cuando corresponda, se formalizarán con dichos proveedores los acuerdos y garantías exigidos por la normativa aplicable en materia de protección de datos.",
        ],
      },
      {
        title: "8. Transferencias internacionales",
        body: [
          "Algunos de los proveedores tecnológicos utilizados por 3DCosprops pueden almacenar o tratar determinados datos fuera del Espacio Económico Europeo.",
          "Cuando se produzcan transferencias internacionales de datos personales, 3DCosprops adoptará las medidas y garantías exigidas por la normativa aplicable, incluyendo, cuando corresponda, decisiones de adecuación, cláusulas contractuales tipo u otros mecanismos legalmente reconocidos.",
          "La relación definitiva de proveedores, localizaciones de tratamiento y mecanismos utilizados se concretará antes de la puesta en producción definitiva del sitio web.",
        ],
      },
      {
        title: "9. Conservación de los datos",
        body: [
          "Los datos personales se conservarán durante el tiempo necesario para cumplir la finalidad para la que fueron recopilados.",
          "Con carácter general:",
          "- Los datos de una cuenta de usuario se conservarán mientras la cuenta permanezca activa, salvo que exista una obligación legal de conservarlos durante más tiempo.",
          "- Los datos relacionados con consultas se conservarán durante el tiempo necesario para gestionar y resolver la solicitud.",
          "- Los datos relacionados con operaciones comerciales o contractuales se conservarán durante los plazos legalmente exigibles.",
          "- Los datos utilizados para comunicaciones comerciales se conservarán mientras el usuario no retire su consentimiento o solicite su supresión, sin perjuicio de otras obligaciones legales.",
          "- Determinados datos técnicos y registros podrán conservarse durante el tiempo necesario para garantizar la seguridad de la plataforma y detectar posibles incidencias.",
          "Una vez finalizados los plazos correspondientes, los datos serán eliminados o, cuando proceda, anonimizados.",
        ],
      },
      {
        title: "10. Seguridad de los datos",
        body: [
          "3DCosprops aplica medidas técnicas y organizativas destinadas a proteger los datos personales frente a pérdida, destrucción, acceso no autorizado, alteración o divulgación indebida.",
          "Entre otras medidas, podrán aplicarse:",
          "- Comunicaciones cifradas mediante HTTPS.",
          "- Control de acceso a los sistemas.",
          "- Gestión de permisos y privilegios.",
          "- Medidas de autenticación.",
          "- Protección de las credenciales.",
          "- Copias de seguridad cuando corresponda.",
          "- Monitorización y medidas destinadas a prevenir usos indebidos.",
          "- Limitación del acceso a los datos personales al personal o proveedores que necesiten acceder a ellos para desarrollar sus funciones.",
          "No obstante, ningún sistema conectado a Internet puede garantizar una seguridad absoluta.",
          "Las medidas concretas se revisarán periódicamente en función de la evolución tecnológica, los riesgos existentes y las características de los tratamientos realizados.",
        ],
      },
      {
        title: "11. Derechos de los usuarios",
        body: [
          "El usuario puede ejercer, cuando sean aplicables, los siguientes derechos:",
          "- Derecho de acceso: conocer si estamos tratando sus datos personales y obtener información sobre dicho tratamiento.",
          "- Derecho de rectificación: solicitar la corrección de datos personales inexactos o incompletos.",
          "- Derecho de supresión: solicitar la eliminación de sus datos personales cuando concurran las circunstancias previstas legalmente.",
          "- Derecho a la limitación del tratamiento: solicitar que se limite el tratamiento de sus datos en determinados supuestos.",
          "- Derecho de oposición: oponerse a determinados tratamientos de sus datos personales.",
          "- Derecho a la portabilidad: recibir determinados datos personales en un formato estructurado, de uso común y lectura mecánica, cuando resulte aplicable.",
          "- Derecho a retirar el consentimiento: retirar el consentimiento otorgado para aquellos tratamientos basados en él.",
          "",
          "Para ejercer estos derechos, el usuario puede enviar una solicitud a:",
          "",
          "[EMAIL DE PRIVACIDAD / EMAIL DE CONTACTO]",
          "",
          "La solicitud deberá incluir, cuando sea necesario, información suficiente para verificar la identidad del solicitante.",
          "El ejercicio de estos derechos es, con carácter general, gratuito.",
        ],
      },
      {
        title: "12. Derecho a presentar una reclamación",
        body: [
          "Si el usuario considera que sus derechos en materia de protección de datos no han sido respetados, puede presentar una reclamación ante la autoridad de control competente.",
          "En España, la autoridad de control es:",
          "Agencia Española de Protección de Datos (AEPD)",
          "Sitio web: https://www.aepd.es/",
          "Antes de presentar una reclamación, recomendamos que el usuario se ponga en contacto con nosotros para intentar resolver cualquier cuestión relacionada con el tratamiento de sus datos.",
        ],
      },
      {
        title: "13. Cookies",
        body: [
          "El sitio web puede utilizar cookies y tecnologías similares.",
          "Las cookies pueden ser necesarias para el funcionamiento técnico de la plataforma, la autenticación de usuarios, la seguridad, la personalización o, cuando corresponda, para obtener estadísticas y analizar el uso del sitio web.",
          "Las cookies que no sean estrictamente necesarias estarán sujetas, cuando corresponda, a los mecanismos de información y consentimiento exigidos por la normativa aplicable.",
          "La información detallada sobre las cookies utilizadas por 3DCosprops, su finalidad, duración, proveedor y posibilidad de aceptación o rechazo se recogerá en la correspondiente Política de Cookies.",
        ],
      },
      {
        title: "14. Servicios de terceros",
        body: [
          "El sitio web puede contener enlaces o integraciones con servicios de terceros.",
          "Cuando el usuario interactúa con dichos servicios, puede estar sujeto a sus propias condiciones de uso y políticas de privacidad.",
          "3DCosprops no será responsable del tratamiento de datos que dichos terceros realicen bajo sus own condiciones, salvo cuando actúen como proveedores contratados por 3DCosprops para prestar un servicio determinado.",
        ],
      },
      {
        title: "15. Menores de edad",
        body: [
          "Los servicios de 3DCosprops no están dirigidos específicamente a menores de edad, salvo que se indique expresamente lo contrario.",
          "Si consideramos que se han recopilado datos personales de un menor sin la autorización o base jurídica necesaria, podremos adoptar las medidas oportunas para eliminar dichos datos.",
        ],
      },
      {
        title: "16. Decisiones automatizadas y elaboración de perfiles",
        body: [
          "Con carácter general, 3DCosprops no tomará decisiones basadas únicamente en tratamientos automatizados que produzcan efectos jurídicos o efectos significativamente similares sobre los usuarios.",
          "[REVISAR ESTA SECCIÓN SI EN EL FUTURO SE INCORPORAN SISTEMAS DE RECOMENDACIÓN, PERSONALIZACIÓN, PUNTUACIÓN DE USUARIOS, IA, PROFILING U OTROS SISTEMAS AUTOMATIZADOS.]",
        ],
      },
      {
        title: "17. Actualizaciones de esta Política de Privacidad",
        body: [
          "Esta Política de Privacidad podrá modificarse cuando sea necesario para adaptarla a cambios legales, tecnológicos, funcionales o relacionados con los servicios ofrecidos por 3DCosprops.",
          "La versión vigente será la publicada en esta página.",
          "Cuando los cambios sean relevantes, podremos comunicarlo mediante los medios disponibles cuando resulte necesario.",
          "Fecha de última actualización: [FECHA]",
        ],
      },
      {
        title: "18. Contacto",
        body: [
          "Si tienes cualquier pregunta relacionada con esta Política de Privacidad o con el tratamiento de tus datos personales, puedes contactar con nosotros mediante:",
          "3DCosprops",
          "Email: [EMAIL]",
          "Dirección: [DIRECCIÓN]",
          "Sitio web: https://3dcosprops.com/",
        ],
      },
    ],
  },

  cookiePolicy: {
    title: "Política de Cookies",
    lastUpdated: "[FECHA]",
    disclaimer:
      "⚠️ Este documento es un MOCKUP no definitivo. Los campos marcados entre corchetes [ ] deben completarse con los datos reales antes de la publicación oficial.",
    sections: [
      {
        title: "1. ¿Qué son las cookies?",
        body: [
          "Las cookies son pequeños archivos que se almacenan en el dispositivo del usuario cuando visita determinadas páginas web.",
          "Permiten, entre otras funciones, recordar información sobre la navegación, mantener determinadas funcionalidades técnicas, gestionar sesiones de usuario o recopilar información sobre el uso de una página web.",
          "Las cookies pueden ser propias, cuando son gestionadas directamente por el titular del sitio web, o de terceros, cuando son gestionadas por otros proveedores.",
        ],
      },
      {
        title: "2. ¿Qué cookies utiliza 3DCosprops?",
        body: [
          "El sitio web de 3DCosprops puede utilizar diferentes categorías de cookies dependiendo de las funcionalidades activas en cada momento.",
          "La relación definitiva deberá actualizarse cuando se incorporen nuevos servicios o herramientas.",
          "",
          "2.1. Cookies técnicas o necesarias",
          "Son aquellas necesarias para el funcionamiento básico del sitio web y para proporcionar determinados servicios solicitados por el usuario.",
          "Pueden utilizarse, por ejemplo, para:",
          "- Mantener sesiones de usuario.",
          "- Gestionar la autenticación.",
          "- Mantener la seguridad.",
          "- Recordar determinadas preferencias técnicas.",
          "- Gestionar determinadas funcionalidades de la aplicación.",
          "- Prevenir usos fraudulentos.",
          "- Permitir el correcto funcionamiento de la plataforma.",
          "Estas cookies son necesarias para determinadas funcionalidades del sitio y, cuando se encuentren dentro de las excepciones legalmente previstas, no requieren consentimiento.",
          "",
          "Cookies concretas utilizadas:",
          "| Cookie | Proveedor | Finalidad | Duración |",
          "|--------|-----------|-----------|----------|",
          "| [NOMBRE] | 3DCosprops / Supabase | [FINALIDAD] | [DURACIÓN] |",
          "| [NOMBRE] | [PROVEEDOR] | [FINALIDAD] | [DURACIÓN] |",
          "",
          "2.2. Cookies de preferencias o personalización",
          "[ELIMINAR ESTA SECCIÓN SI NO SE UTILIZAN.]",
          "Estas cookies permiten recordar determinadas preferencias del usuario, como:",
          "- Idioma.",
          "- Preferencias de visualización.",
          "- Configuración de la interfaz.",
          "- Otras preferencias seleccionadas directamente por el usuario.",
          "",
          "2.3. Cookies de análisis o medición",
          "[ELIMINAR ESTA SECCIÓN SI NO SE UTILIZAN.]",
          "Si 3DCosprops utiliza herramientas de analítica web, determinadas cookies podrán utilizarse para conocer cómo utilizan los usuarios el sitio web.",
          "La información obtenida podrá utilizarse para:",
          "- Medir visitas.",
          "- Analizar el uso de diferentes páginas.",
          "- Detectar problemas de navegación.",
          "- Mejorar el funcionamiento del sitio.",
          "- Obtener estadísticas.",
          "",
          "2.4. Cookies de publicidad o marketing",
          "[ELIMINAR COMPLETAMENTE SI NO SE UTILIZAN.]",
          "En caso de que 3DCosprops incorpore herramientas publicitarias o de remarketing, podrán utilizarse cookies destinadas a:",
          "- Mostrar publicidad.",
          "- Medir campañas publicitarias.",
          "- Crear perfiles publicitarios.",
          "- Realizar remarketing.",
          "- Medir conversiones.",
        ],
      },
      {
        title: "3. Cookies de terceros",
        body: [
          "Algunas funcionalidades del sitio web pueden depender de servicios proporcionados por terceros.",
          "Dependiendo de la configuración final de la plataforma, estos servicios podrían incluir:",
          "- Supabase.",
          "- Vercel.",
          "- Resend.",
          "- Servicios de analítica.",
          "- Servicios de mapas.",
          "- Servicios de vídeo.",
          "- Redes sociales.",
          "- Proveedores de pago.",
          "- Otros servicios integrados en la plataforma.",
          "La utilización concreta de cookies o tecnologías similares por parte de estos proveedores dependerá de las integraciones activas en cada momento.",
        ],
      },
      {
        title: "4. Gestión del consentimiento",
        body: [
          "Cuando sea necesario obtener el consentimiento para determinadas cookies, 3DCosprops proporcionará al usuario un mecanismo que permita:",
          "- Aceptar las cookies.",
          "- Rechazar las cookies no necesarias.",
          "- Configurar las preferencias por categorías.",
          "- Modificar posteriormente las preferencias.",
          "La opción de rechazar las cookies no necesarias estará disponible de forma clara y accesible.",
          "El usuario podrá modificar sus preferencias en cualquier momento mediante:",
          "[ENLACE / BOTÓN \"CONFIGURAR COOKIES\"]",
        ],
      },
      {
        title: "5. Cookies necesarias",
        body: [
          "Las cookies estrictamente necesarias para proporcionar un servicio solicitado por el usuario o para determinadas funcionalidades técnicas podrán utilizarse sin consentimiento cuando estén legalmente exceptuadas.",
          "No obstante, 3DCosprops informará de su utilización de acuerdo con los requisitos de transparencia aplicables.",
        ],
      },
      {
        title: "6. Cookies y datos personales",
        body: [
          "En determinadas circunstancias, la información recopilada mediante cookies puede estar relacionada con una persona identificable y, por tanto, constituir un dato personal.",
          "En esos casos, el tratamiento se realizará de acuerdo con la Política de Privacidad de 3DCosprops y con la normativa aplicable en materia de protección de datos.",
        ],
      },
      {
        title: "7. Configuración del navegador",
        body: [
          "El usuario también puede configurar su navegador para bloquear o eliminar determinadas cookies.",
          "Los procedimientos concretos dependen del navegador utilizado.",
          "Sin embargo, el bloqueo de determinadas cookies técnicas puede afectar al funcionamiento de algunas funcionalidades de 3DCosprops.",
        ],
      },
      {
        title: "8. Actualización de la Política de Cookies",
        body: [
          "Esta Política de Cookies podrá modificarse cuando:",
          "- Se incorporen nuevas funcionalidades.",
          "- Se incorporen nuevos proveedores.",
          "- Se modifique la configuración técnica.",
          "- Cambie la normativa aplicable.",
          "- Se modifiquen las cookies utilizadas.",
          "La versión vigente será siempre la publicada en esta página.",
          "Última actualización: [FECHA]",
        ],
      },
      {
        title: "9. Contacto",
        body: [
          "Si tienes alguna pregunta sobre el uso de cookies en 3DCosprops, puedes contactar con nosotros:",
          "Email: [EMAIL]",
          "Titular: [NOMBRE / EMPRESA]",
        ],
      },
    ],
  },

  legalNotice: {
    title: "Aviso Legal",
    lastUpdated: "[FECHA]",
    disclaimer:
      "⚠️ Este documento es un MOCKUP no definitivo. Los campos marcados entre corchetes [ ] deben completarse con los datos reales antes de la publicación oficial.",
    sections: [
      {
        title: "1. Información general",
        body: [
          'En cumplimiento de lo establecido en la legislación aplicable a los servicios de la sociedad de la información y comercio electrónico, se facilita a continuación la información general del titular del sitio web:',
          'Titular: [NOMBRE Y APELLIDOS / RAZÓN SOCIAL]',
          'NIF/CIF: [NIF/CIF]',
          'Domicilio: [DIRECCIÓN COMPLETA]',
          'Correo electrónico: [EMAIL DE CONTACTO]',
          'Teléfono: [TELÉFONO, SI PROCEDE]',
          'Dominio: https://3dcosprops.com/',
          '',
          'Datos de inscripción registral:',
          '[REGISTRO, TOMO, FOLIO, HOJA, INSCRIPCIÓN, ETC., SI PROCEDE]',
          '',
          'En adelante, el titular será denominado 3DCosprops.',
        ],
      },
      {
        title: "2. Objeto",
        body: [
          "El presente Aviso Legal regula el acceso y utilización del sitio web 3dcosprops.com, así como las responsabilidades derivadas de su utilización.",
          "El acceso y navegación por el sitio web implica la aceptación de las condiciones recogidas en este Aviso Legal.",
          "Si el usuario no está de acuerdo con alguna de estas condiciones, deberá abstenerse de utilizar el sitio web.",
          "Determinados servicios o funcionalidades de la plataforma pueden estar sujetos, además, a condiciones específicas que serán comunicadas al usuario cuando corresponda.",
        ],
      },
      {
        title: "3. Descripción del servicio",
        body: [
          "3DCosprops es una plataforma relacionada con [DESCRIBIR BREVEMENTE LA ACTIVIDAD: DISEÑO, FABRICACIÓN, VENTA Y/O DISTRIBUCIÓN DE PROPS, ACCESORIOS, ARCHIVOS 3D, SERVICIOS DE IMPRESIÓN 3D, ETC.].",
          "A través del sitio web podrán ofrecerse, dependiendo de la versión y funcionalidades disponibles:",
          "- Información sobre productos y servicios.",
          "- Catálogos de productos.",
          "- Productos físicos.",
          "- Archivos digitales.",
          "- Servicios relacionados con impresión o fabricación 3D.",
          "- Formularios de contacto.",
          "- Cuentas de usuario.",
          "- Sistemas de pedidos o solicitudes.",
          "- Comunicaciones electrónicas.",
          "- Otras funcionalidades que se incorporen posteriormente.",
          "Las funcionalidades disponibles podrán modificarse, ampliarse, limitarse o eliminarse en cualquier momento.",
        ],
      },
      {
        title: "4. Condiciones de acceso y utilización",
        body: [
          "El acceso al sitio web es, con carácter general, gratuito, sin perjuicio de los productos o servicios que puedan requerir un pago.",
          "El usuario se compromete a utilizar el sitio web de forma lícita, diligente y de acuerdo con:",
          "- La legislación vigente.",
          "- El presente Aviso Legal.",
          "- Las condiciones particulares que resulten aplicables.",
          "- Las buenas prácticas generalmente aceptadas en Internet.",
          "Queda prohibido utilizar el sitio web para:",
          "- Realizar actividades ilícitas.",
          "- Intentar acceder sin autorización a sistemas o cuentas.",
          "- Interferir en el funcionamiento de la plataforma.",
          "- Introducir malware, virus u otro software malicioso.",
          "- Realizar actividades fraudulentas.",
          "- Obtener o recopilar información de otros usuarios sin autorización.",
          "- Utilizar mecanismos automatizados que puedan perjudicar el funcionamiento del servicio.",
          "- Vulnerar derechos de terceros.",
          "- Utilizar los contenidos de la plataforma con fines contrarios a la legislación aplicable.",
        ],
      },
      {
        title: "5. Registro de usuarios",
        body: [
          "Determinadas funcionalidades pueden requerir la creación de una cuenta.",
          "Cuando sea necesario registrarse, el usuario deberá proporcionar información veraz, actualizada y completa.",
          "El usuario será responsable de mantener la confidencialidad de sus credenciales de acceso y de todas las actividades realizadas desde su cuenta, salvo que pueda demostrarse que dichas actividades se han producido por causas no imputables al usuario.",
          "Si el usuario detecta un acceso no autorizado o cualquier problema de seguridad relacionado con su cuenta, deberá comunicarlo a 3DCosprops lo antes posible.",
          "3DCosprops podrá suspender o cancelar cuentas cuando existan motivos razonables para considerar que se están utilizando de forma fraudulenta, ilícita o contraria a estas condiciones.",
        ],
      },
      {
        title: "6. Propiedad intelectual e industrial",
        body: [
          "Todos los contenidos disponibles en el sitio web, incluyendo, entre otros:",
          "- Textos.",
          "- Fotografías.",
          "- Ilustraciones.",
          "- Diseños.",
          "- Modelos 3D.",
          "- Archivos digitales.",
          "- Logotipos.",
          "- Marcas.",
          "- Elementos gráficos.",
          "- Código fuente.",
          "- Diseño y estructura del sitio web.",
          "- Vídeos.",
          "- Otros elementos audiovisuales.",
          "podrán estar protegidos por derechos de propiedad intelectual o industrial.",
          "Salvo que se indique expresamente lo contrario, dichos derechos corresponden a 3DCosprops o a sus respectivos titulares.",
          "El acceso al sitio web no implica la cesión al usuario de ningún derecho de propiedad intelectual o industrial.",
          "Queda prohibida la reproducción, distribución, transformación, comunicación pública, puesta a disposición o explotación de los contenidos sin la correspondiente autorización, salvo cuando dicha utilización esté permitida por la legislación aplicable o por las condiciones específicas del contenido.",
          "",
          "Contenido de terceros",
          "Cuando se incorporen contenidos, marcas, diseños, referencias o materiales pertenecientes a terceros, estos seguirán siendo propiedad de sus respectivos titulares.",
          "[SI 3DCOSPROPS VENDE DISEÑOS RELACIONADOS CON PERSONAJES/FRANQUICIAS DE TERCEROS, AÑADIR AQUÍ UNA CLÁUSULA ESPECÍFICA SOBRE LICENCIAS, FAN ART Y RESPONSABILIDAD.]",
        ],
      },
      {
        title: "7. Contenidos aportados por los usuarios",
        body: [
          "Si la plataforma permite a los usuarios subir fotografías, modelos 3D, comentarios, diseños, archivos u otros contenidos, el usuario declara que dispone de los derechos necesarios para proporcionar dichos contenidos.",
          "El usuario será responsable de que los contenidos aportados:",
          "- No infrinjan derechos de propiedad intelectual o industrial.",
          "- No vulneren derechos de imagen o privacidad.",
          "- No sean ilícitos.",
          "- No contengan malware.",
          "- No infrinjan derechos de terceros.",
          "El usuario mantendrá la titularidad de sus contenidos, salvo que las condiciones específicas del servicio establezcan otra cosa.",
          "[REVISAR ESTA SECCIÓN SI SE INCORPORA UNA GALERÍA, MARKETPLACE, SISTEMA DE SUBIDA DE STL U OTRAS FUNCIONES DE CONTENIDO GENERADO POR USUARIOS.]",
        ],
      },
      {
        title: "8. Disponibilidad del sitio web",
        body: [
          "3DCosprops procurará mantener el sitio web disponible y funcionando correctamente.",
          "No obstante, no se garantiza la disponibilidad permanente del servicio.",
          "El sitio web puede quedar temporalmente inaccesible debido, entre otras causas, a:",
          "- Trabajos de mantenimiento.",
          "- Actualizaciones.",
          "- Fallos técnicos.",
          "- Problemas de conectividad.",
          "- Incidencias de proveedores externos.",
          "- Ataques informáticos.",
          "- Circunstancias de fuerza mayor.",
          "Cuando sea posible, se procurará informar previamente de las interrupciones programadas.",
        ],
      },
      {
        title: "9. Enlaces externos",
        body: [
          "El sitio web puede contener enlaces a páginas, servicios o plataformas de terceros.",
          "Estos enlaces se proporcionan con fines informativos o funcionales.",
          "3DCosprops no controla necesariamente el contenido, disponibilidad, políticas de privacidad o condiciones de uso de dichos sitios externos y, salvo que la legislación establezca otra cosa, no será responsable de los contenidos o servicios ofrecidos por terceros.",
        ],
      },
      {
        title: "10. Responsabilidad",
        body: [
          "3DCosprops procurará que la información publicada en el sitio web sea correcta y esté actualizada.",
          "No obstante, pueden existir errores, omisiones o información que haya quedado desactualizada.",
          "El usuario utiliza el sitio web bajo su propia responsabilidad.",
          "3DCosprops no será responsable, dentro de los límites permitidos por la legislación aplicable, de los daños derivados de:",
          "- Uso incorrecto del sitio web.",
          "- Imposibilidad temporal de acceso.",
          "- Fallos de terceros.",
          "- Virus u otros elementos dañinos que puedan existir en Internet.",
          "- Uso indebido de las cuentas de usuario.",
          "- Contenidos aportados por terceros.",
          "Lo anterior se entiende sin perjuicio de las responsabilidades que legalmente no puedan excluirse o limitarse.",
        ],
      },
      {
        title: "11. Protección de datos",
        body: [
          "El tratamiento de los datos personales de los usuarios se realizará de acuerdo con nuestra Política de Privacidad.",
          "Puedes consultar dicha política en la sección de Política de Privacidad de este sitio web.",
        ],
      },
      {
        title: "12. Cookies",
        body: [
          "El sitio web puede utilizar cookies y tecnologías similares.",
          "La información relativa a las cookies utilizadas, sus finalidades y la forma de gestionar las preferencias se encuentra disponible en nuestra Política de Cookies.",
        ],
      },
      {
        title: "13. Modificaciones",
        body: [
          "3DCosprops podrá modificar el contenido del sitio web y del presente Aviso Legal cuando resulte necesario.",
          "La versión vigente será la publicada en esta página.",
          "Cuando los cambios sean relevantes, podrán comunicarse mediante los medios disponibles cuando resulte apropiado.",
        ],
      },
      {
        title: "14. Legislación aplicable y jurisdicción",
        body: [
          "La relación entre 3DCosprops y el usuario se regirá por la legislación española, sin perjuicio de las normas imperativas que puedan resultar aplicables en función de la condición del usuario y de su lugar de residencia.",
          "Cuando el usuario tenga la condición legal de consumidor, serán aplicables las normas de protección de consumidores y usuarios que correspondan.",
          "Para la resolución de controversias se estará a los juzgados y tribunales que resulten competentes conforme a la legislación aplicable.",
        ],
      },
      {
        title: "15. Contacto",
        body: [
          "Para cualquier cuestión relacionada con este sitio web, puede contactar con:",
          "3DCosprops",
          "Email: [EMAIL]",
          "Dirección: [DIRECCIÓN]",
          "Teléfono: [TELÉFONO, SI PROCEDE]",
          "Última actualización: [FECHA]",
        ],
      },
    ],
  },

  termsConditions: {
    title: "Términos y Condiciones de Uso y Compra",
    lastUpdated: "[FECHA]",
    disclaimer:
      "⚠️ Este documento es un MOCKUP no definitivo. Los campos marcados entre corchetes [ ] deben completarse con los datos reales antes de la publicación oficial.",
    sections: [
      {
        title: "1. Identificación",
        body: [
          "Los presentes Términos y Condiciones regulan el uso del sitio web https://3dcosprops.com/ y, cuando corresponda, la adquisición de productos y servicios ofrecidos a través del mismo.",
          "Titular: [NOMBRE / RAZÓN SOCIAL]",
          "NIF/CIF: [NIF/CIF]",
          "Domicilio: [DIRECCIÓN]",
          "Email: [EMAIL]",
          "Web: https://3dcosprops.com/",
          "En adelante, 3DCosprops.",
        ],
      },
      {
        title: "2. Aceptación de las condiciones",
        body: [
          "El acceso y utilización del sitio web implica la aceptación de estos Términos y Condiciones.",
          "Cuando el usuario realice una compra, contratación o solicitud a través de la plataforma, deberá aceptar expresamente las condiciones que resulten aplicables.",
          "Si el usuario no está de acuerdo con estas condiciones, deberá abstenerse de utilizar los servicios correspondientes.",
        ],
      },
      {
        title: "3. Funcionamiento de la plataforma",
        body: [
          "3DCosprops puede ofrecer a través de su plataforma diferentes tipos de productos y servicios, entre ellos:",
          "- Props y accesorios.",
          "- Productos físicos.",
          "- Modelos y archivos 3D.",
          "- Archivos digitales descargables.",
          "- Servicios de impresión 3D.",
          "- Servicios de fabricación.",
          "- Productos personalizados.",
          "- Encargos.",
          "- Otros productos o servicios relacionados con el ámbito de 3DCosprops.",
          "La disponibilidad concreta de cada producto o servicio se indicará en su correspondiente página.",
          "3DCosprops se reserva el derecho de modificar, actualizar o retirar productos y servicios.",
        ],
      },
      {
        title: "4. Cuenta de usuario",
        body: [
          "Algunas funcionalidades pueden requerir la creación de una cuenta.",
          "El usuario se compromete a proporcionar información verdadera y mantenerla actualizada.",
          "El usuario es responsable de mantener la confidencialidad de sus credenciales.",
          "No está permitido:",
          "- Compartir deliberadamente una cuenta cuando las condiciones del servicio no lo permitan.",
          "- Crear cuentas con datos falsos.",
          "- Utilizar cuentas de terceros sin autorización.",
          "- Utilizar el sistema de cuentas para actividades fraudulentas.",
          "3DCosprops podrá suspender o cancelar cuentas que incumplan estos Términos y Condiciones o que puedan representar un riesgo para la seguridad de la plataforma.",
        ],
      },
      {
        title: "5. Productos físicos",
        body: [
          "[CONSERVAR ESTA SECCIÓN SI SE VENDERÁN PRODUCTOS FÍSICOS.]",
          "Las características principales de cada producto serán indicadas en su correspondiente ficha.",
          "Las fotografías utilizadas en el sitio web tienen carácter ilustrativo cuando así se indique.",
          "Podrían existir pequeñas diferencias entre las imágenes mostradas y el producto final debido a factores como:",
          "- Pantalla utilizada.",
          "- Iluminación.",
          "- Material.",
          "- Acabado.",
          "- Proceso de fabricación.",
          "- Personalización solicitada.",
          "Estas diferencias no afectarán a las características esenciales del producto.",
        ],
      },
      {
        title: "6. Productos personalizados",
        body: [
          "[CONSERVAR SI HABRÁ PERSONALIZACIÓN.]",
          "Cuando un producto sea fabricado o modificado siguiendo instrucciones específicas del cliente, se considerará un producto personalizado en los términos establecidos por la legislación aplicable.",
          "El usuario será responsable de comprobar que los datos proporcionados para la personalización son correctos.",
          "3DCosprops no será responsable de errores derivados de información incorrecta proporcionada por el cliente.",
          "Cuando un pedido personalizado requiera confirmación previa, la producción podrá comenzar únicamente después de dicha confirmación.",
        ],
      },
      {
        title: "7. Archivos digitales",
        body: [
          "[CONSERVAR SI SE VENDERÁN STL, OBJ, 3MF U OTROS ARCHIVOS DIGITALES.]",
          "Los archivos digitales ofrecidos a través de 3DCosprops están destinados al uso especificado en la correspondiente ficha del producto.",
          "La compra de un archivo digital no implica la transmisión de la propiedad intelectual sobre el diseño.",
          "Salvo que se indique expresamente lo contrario, el usuario adquiere únicamente una licencia de uso del archivo bajo las condiciones indicadas en la página del producto.",
          "Queda prohibido, salvo autorización expresa:",
          "- Revender los archivos.",
          "- Redistribuirlos.",
          "- Compartirlos públicamente.",
          "- Subirlos a plataformas de descarga.",
          "- Utilizarlos para crear un servicio de distribución de archivos.",
          "- Modificarlos y redistribuir las modificaciones cuando la licencia no lo permita.",
          "- Comercializar copias digitales del archivo.",
          "",
          "Impresión física",
          "[DECIDIR SI LOS STL PUEDEN UTILIZARSE PARA CREAR PRODUCTOS FÍSICOS DESTINADOS A LA VENTA.]",
          "La licencia aplicable a cada archivo deberá especificar claramente si permite:",
          "[USO PERSONAL ÚNICAMENTE / USO COMERCIAL / FABRICACIÓN Y VENTA / OTRO]",
        ],
      },
      {
        title: "8. Propiedad intelectual de los diseños",
        body: [
          "Los diseños, modelos 3D, fotografías, textos, gráficos y demás contenidos ofrecidos por 3DCosprops pueden estar protegidos por derechos de propiedad intelectual.",
          "La compra de un producto o archivo no supone la transmisión de dichos derechos salvo indicación expresa.",
          "El usuario deberá respetar las condiciones de licencia asociadas a cada producto.",
          "Cuando un producto esté basado en una propiedad intelectual perteneciente a un tercero, 3DCosprops indicará, cuando corresponda, la naturaleza de dicha relación o autorización.",
        ],
      },
      {
        title: "9. Precios",
        body: [
          "Los precios de los productos serán los indicados en el sitio web en cada momento.",
          "Los precios podrán mostrarse:",
          "[CON IVA INCLUIDO / SIN IVA, SEGÚN CORRESPONDA]",
          "Cuando resulte aplicable, se indicarán de forma separada los gastos de envío, impuestos u otros costes adicionales.",
          "Los precios pueden modificarse en cualquier momento.",
          "Los cambios no afectarán a los pedidos que ya hayan sido confirmados, salvo en los casos legalmente previstos.",
        ],
      },
      {
        title: "10. Proceso de compra",
        body: [
          "El proceso de compra podrá incluir, de forma general, los siguientes pasos:",
          "- Selección del producto.",
          "- Añadir el producto al carrito.",
          "- Revisión del pedido.",
          "- Introducción de los datos necesarios.",
          "- Selección del método de pago.",
          "- Aceptación de los términos y condiciones.",
          "- Confirmación del pedido.",
          "- Realización del pago.",
          "- Envío de la confirmación correspondiente.",
          "Antes de finalizar el pedido, el usuario podrá revisar los datos introducidos y corregir posibles errores.",
          "La confirmación de la compra será enviada al correo electrónico proporcionado por el usuario.",
        ],
      },
      {
        title: "11. Métodos de pago",
        body: [
          "Los métodos de pago disponibles serán indicados durante el proceso de compra.",
          "Métodos previstos:",
          "[STRIPE]",
          "[PAYPAL]",
          "[TRANSFERENCIA]",
          "[OTROS]",
          "Los datos de pago podrán ser procesados directamente por proveedores especializados de servicios de pago.",
          "Cuando el pago sea procesado por un tercero, dicho proveedor podrá aplicar sus propias condiciones y políticas de privacidad.",
          "[COMPLETAR CUANDO SE DEFINA EL PROVEEDOR DE PAGOS.]",
        ],
      },
      {
        title: "12. Envíos",
        body: [
          "[CONSERVAR SI SE VENDEN PRODUCTOS FÍSICOS.]",
          "Los pedidos físicos serán enviados a la dirección indicada por el cliente.",
          "Las zonas de envío disponibles serán:",
          "[ESPAÑA / UNIÓN EUROPEA / INTERNACIONAL / OTRAS]",
          "Los gastos de envío se mostrarán antes de finalizar la compra.",
          "Los plazos de entrega serán indicativos cuando así se especifique.",
          "Los retrasos ocasionados por empresas de transporte, aduanas u otras circunstancias ajenas al control razonable de 3DCosprops no serán considerados incumplimientos cuando legalmente no pueda imputarse responsabilidad a 3DCosprops.",
        ],
      },
      {
        title: "13. Derecho de desistimiento",
        body: [
          "Cuando el cliente tenga la condición de consumidor, podrá disponer del derecho de desistimiento en los casos y dentro del plazo establecidos por la legislación aplicable.",
          "Con carácter general, el plazo legal de desistimiento para contratos a distancia es de 14 días naturales, salvo las excepciones previstas legalmente.",
          "",
          "Excepciones",
          "Entre otros supuestos, pueden existir excepciones al derecho de desistimiento para determinados productos o servicios, incluyendo, cuando se cumplan los requisitos legales:",
          "- Productos confeccionados conforme a las especificaciones del consumidor o claramente personalizados.",
          "- Determinados contenidos digitales no prestados en soporte material cuando haya comenzado su ejecución con el consentimiento previo y expreso del consumidor y con el reconocimiento de que pierde su derecho de desistimiento.",
          "- Otros supuestos legalmente establecidos.",
          "En el caso de contenidos digitales descargables, el usuario será informado de las condiciones específicas aplicables antes de completar la compra.",
          "[REVISAR ESTA SECCIÓN CON EL MODELO REAL DE VENTA.]",
        ],
      },
      {
        title: "14. Garantía legal y conformidad",
        body: [
          "Los productos vendidos a consumidores estarán sujetos a la garantía legal de conformidad que corresponda de acuerdo con la legislación aplicable.",
          "Cuando un producto presente una falta de conformidad, el consumidor podrá ejercer los derechos que legalmente correspondan.",
          "La garantía legal no cubre daños producidos por:",
          "- Uso incorrecto.",
          "- Manipulación inadecuada.",
          "- Modificaciones no autorizadas.",
          "- Desgaste normal cuando corresponda.",
          "- Daños accidentales.",
          "- Incumplimiento de las instrucciones de utilización.",
          "Lo anterior se entiende sin perjuicio de los derechos que legalmente correspondan al consumidor.",
        ],
      },
      {
        title: "15. Devoluciones",
        body: [
          "Las solicitudes de devolución deberán realizarse mediante:",
          "Email: [EMAIL]",
          "El usuario deberá indicar:",
          "- Número de pedido.",
          "- Nombre.",
          "- Producto.",
          "- Motivo de la solicitud, cuando sea necesario.",
          "Los procedimientos y costes asociados a la devolución dependerán de si se trata de un ejercicio del derecho de desistimiento, una falta de conformidad, un producto defectuoso o cualquier otra causa.",
        ],
      },
      {
        title: "16. Pedidos cancelados",
        body: [
          "3DCosprops podrá cancelar un pedido en circunstancias excepcionales, como:",
          "- Imposibilidad de suministro.",
          "- Error manifiesto en el precio.",
          "- Error técnico grave.",
          "- Sospecha razonable de fraude.",
          "- Circunstancias de fuerza mayor.",
          "Cuando corresponda, el importe pagado será reembolsado mediante el mismo método de pago utilizado por el cliente, salvo que se acuerde otro procedimiento legalmente válido.",
        ],
      },
      {
        title: "17. Obligaciones del usuario",
        body: [
          "El usuario se compromete a:",
          "- Utilizar la plataforma de forma legal.",
          "- Facilitar información correcta.",
          "- No utilizar la plataforma para actividades fraudulentas.",
          "- No vulnerar los derechos de terceros.",
          "- Respetar las licencias de los archivos digitales.",
          "- No intentar comprometer la seguridad de la plataforma.",
          "- No distribuir malware.",
          "- No realizar actividades que puedan perjudicar el funcionamiento del servicio.",
        ],
      },
      {
        title: "18. Responsabilidad",
        body: [
          "3DCosprops será responsable de los productos y servicios en los términos establecidos por la legislación aplicable.",
          "No obstante, no será responsable de daños derivados de un uso incorrecto de los productos, cuando dicho uso sea contrario a las instrucciones proporcionadas o a su finalidad prevista.",
          "En el caso de productos destinados a cosplay, decoración, exhibición, impresión 3D u otros usos específicos, el usuario deberá seguir las instrucciones y recomendaciones correspondientes.",
          "[SI EXISTEN PRODUCTOS QUE PUEDEN TENER RIESGOS ESPECÍFICOS, AÑADIR AQUÍ ADVERTENCIAS DE SEGURIDAD.]",
        ],
      },
      {
        title: "19. Propiedad intelectual de la plataforma",
        body: [
          "El diseño, código, estructura, contenidos y elementos gráficos de la plataforma pertenecen a 3DCosprops o a sus respectivos titulares.",
          "El usuario no adquiere ningún derecho sobre ellos por el mero uso del sitio web.",
        ],
      },
      {
        title: "20. Privacidad",
        body: [
          "El tratamiento de datos personales se realizará de acuerdo con nuestra Política de Privacidad.",
          "El usuario puede consultar información sobre datos recopilados, finalidades, bases jurídicas, proveedores, conservación, derechos y transferencias internacionales.",
        ],
      },
      {
        title: "21. Cookies",
        body: [
          "El sitio web puede utilizar cookies y tecnologías similares.",
          "La información detallada se encuentra disponible en nuestra Política de Cookies.",
        ],
      },
      {
        title: "22. Comunicaciones electrónicas",
        body: [
          "Cuando el usuario proporcione su dirección de correo electrónico durante un proceso de compra, registro o contacto, podrá recibir comunicaciones necesarias para gestionar dicho servicio.",
          "Estas comunicaciones pueden incluir:",
          "- Confirmaciones de cuenta.",
          "- Recuperación de contraseña.",
          "- Confirmaciones de pedido.",
          "- Información sobre envíos.",
          "- Facturas o documentos relacionados.",
          "- Comunicaciones relacionadas con incidencias.",
          "- Información necesaria para la prestación del servicio.",
          "Las comunicaciones comerciales se enviarán únicamente cuando exista una base jurídica válida para ello y de acuerdo con la normativa aplicable.",
        ],
      },
      {
        title: "23. Modificación de los Términos",
        body: [
          "3DCosprops podrá modificar estos Términos y Condiciones cuando resulte necesario.",
          "Las modificaciones se publicarán en esta página.",
          "Los pedidos ya realizados se regirán por las condiciones vigentes en el momento de su contratación, salvo que legalmente corresponda aplicar otras condiciones.",
        ],
      },
      {
        title: "24. Legislación aplicable",
        body: [
          "Estos Términos y Condiciones se regirán por la legislación española, sin perjuicio de las normas imperativas que puedan resultar aplicables a consumidores residentes en otros países.",
          "Cuando el usuario actúe como consumidor, se respetarán los derechos reconocidos por la legislación de protección de consumidores y usuarios.",
        ],
      },
      {
        title: "25. Resolución de conflictos",
        body: [
          "En caso de controversia, las partes procurarán resolverla de forma amistosa.",
          "Los consumidores podrán utilizar los mecanismos de reclamación y resolución alternativa de litigios que resulten legalmente aplicables.",
          "Cuando corresponda, el consumidor podrá acudir a los organismos de consumo competentes.",
        ],
      },
      {
        title: "26. Contacto",
        body: [
          "Para cualquier consulta relacionada con estos Términos y Condiciones:",
          "3DCosprops",
          "Email: [EMAIL]",
          "Dirección: [DIRECCIÓN]",
          "NIF/CIF: [NIF/CIF]",
          "Última actualización: [FECHA]",
        ],
      },
    ],
  },
};

const en: LegalDictionaries = {
  privacyPolicy: {
    title: "Privacy Policy",
    lastUpdated: "[DATE]",
    disclaimer:
      "⚠️ This document is a DRAFT / MOCKUP and is not final. Fields marked with [ ] must be completed with actual data before official publication.",
    sections: [
      { title: "1. Data Controller", body: ["[TRANSLATION PENDING — Spanish content used as placeholder until final version is provided.]"] },
    ],
  },
  cookiePolicy: {
    title: "Cookie Policy",
    lastUpdated: "[DATE]",
    disclaimer:
      "⚠️ This document is a DRAFT / MOCKUP and is not final. Fields marked with [ ] must be completed with actual data before official publication.",
    sections: [
      { title: "1. What are cookies?", body: ["[TRANSLATION PENDING — Spanish content used as placeholder until final version is provided.]"] },
    ],
  },
  legalNotice: {
    title: "Legal Notice",
    lastUpdated: "[DATE]",
    disclaimer:
      "⚠️ This document is a DRAFT / MOCKUP and is not final. Fields marked with [ ] must be completed with actual data before official publication.",
    sections: [
      { title: "1. General Information", body: ["[TRANSLATION PENDING — Spanish content used as placeholder until final version is provided.]"] },
    ],
  },
  termsConditions: {
    title: "Terms and Conditions of Use and Purchase",
    lastUpdated: "[DATE]",
    disclaimer:
      "⚠️ This document is a DRAFT / MOCKUP and is not final. Fields marked with [ ] must be completed with actual data before official publication.",
    sections: [
      { title: "1. Identification", body: ["[TRANSLATION PENDING — Spanish content used as placeholder until final version is provided.]"] },
    ],
  },
};

export const legalDictionaries: Record<Locale, LegalDictionaries> = { es, en };